### ISSUE TITLE
Add default ordering for images

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#108]
Allow images to be sorted by image name by default.

**Comment by philipbjorge** [comment]
By the tags, I'm assuming that this has to do with how the images are ordered in the administration interface?

I assume we would want them displayed in this manner (note that it's ordered by image name AND weight):

+---------+---------+--------+
| Species |  Image  | Weight |
+---------+---------+--------+
| Aaaa    | Zdorsal | -1     |
| Aaaa    | ventral | 0      |
| Abaa    | zbbb    | 0      |
| Abaa    | zbbc    | 0      |
| abaa    | aaaa    | 1      |
+---------+---------+--------+

This would require ordering like so: ['species', 'weight', 'image']
The Django-Docs state the following:
"Changed in Django Development version.
Django honors all elements in the list/tuple; before 1.4, only the first was respected."
https://docs.djangoproject.com/en/dev/ref/contrib/admin/

To conclude, unless I misunderstood the issue, we'll have to wait to fully implement this feature until we upgrade to django 1.4.

**Comment by huddlej** [comment]
Hey Philip,

Good research! The ordering is primarily for the display on the
website although order on the admin site is of some practical use too.
Outside of the admin interface we have a lot more control over the
ordering of querysets. For the species factsheet pages, we already
have a queryset of images limited to species. From there we just need
to order by weight and display the images.

What I was thinking regarding the current filename scheme and weights
is that we could do an initial parse of all existing images and use
filenames to assign weights.

Kind of off topic, but it occurred to me today that it would be
worthwhile for you to work through the Django tutorials [1] if you
haven't yet. They aren't amazing, but they will help. After the
tutorials, the most important docs to cover are for the models[2],
urls [3], and views [4].

How comfortable do you feel with Django right now given what you've done so far?

/John/

[1] https://docs.djangoproject.com/en/1.3/intro/tutorial01/
[2] https://docs.djangoproject.com/en/1.3/topics/db/models/
[3] https://docs.djangoproject.com/en/1.3/topics/http/urls/
[4] https://docs.djangoproject.com/en/1.3/topics/http/views/

On Wed, Dec 7, 2011 at 3:25 PM, Philip Bjorge
reply@reply.github.com
wrote:

**Comment by philipbjorge** [comment]
Will you handle the script?

I feel fairly comfortable with Django - I dislike that it doesn't force a file/directory structure like Rails - I'm having to do a lot of grepping. It works though :D. I was going to pick up a book in the next couple days to fill in the rest.

Feel free to attach me to whatever issues though - I'll be able to figure them out.
