### ISSUE TITLE
Add "weight" field to species image model

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#109]
Images need an integer field (editable in Django admin) that allows admins to weight specific images differently than others. This weight field should be the default order field and if no weight value is given, ordering should default to alphabetical.

**Comment by philipbjorge** [comment]
Do you have any thoughts on how you want this implemented?

Currently, I'm thinking of giving each species image a default weight of NULL and then displaying images by lowest number first and NULL last (with alphabetical ordering for NULLs).

So images would be displayed as follows:
-1,20,NULL
or
1,2,3,NULL,NULL,NULL

**Comment by huddlej** [comment]
I think the ordering you suggest makes sense for a weight field with higher numbers being heavier. The only change I'd suggest is using 0 for a default instead of NULL. Then you can easily handle the case when you want to demote a set of images below the default rather than promoting them.

The reason why we actually want to be able to order images has more to do with showing dorsal images before ventral in the slideshows and any other image lists. We used to order images by filename to get this effect because images are named like this:

Binomial name-A-D.jpg

where "A" is the first image for that binomial name and "D" is "dorsal". We can't rely on all images following that naming scheme in the future though.

Let me know if this background helps or just makes things more complicated...

**Comment by philipbjorge** [comment]
Do we want to display the heaviest or lightest images first?

**Comment by huddlej** [comment]
If we call the field "weight", it should be the lightest first. If we
call it "priority", it should be the higher numbers first. Whichever
approach you choose, it should be intuitive for Merrill to use. You
might even ask him if he is familiar with the concept of weights in
this context.

/John/

On Tue, Dec 6, 2011 at 9:13 PM, Philip Bjorge
reply@reply.github.com
wrote:
