### ISSUE TITLE
Species_Images Administration rename images

### ISSUE THREAD

**Issue by philipbjorge** [huddlej/pnwmoths#112]
Allow manual renaming of species_images in the administration

This might cause problems with the sorl-thumbnail key-value store?

**Comment by huddlej** [comment]
sorl-thumbnail should generate a new set of thumbnails for any images that get renamed. As long as we know the file system and the SpeciesImage table match, there shouldn't be a problem.

**Comment by philipbjorge** [comment]
This feature needs to be compatible with the zoomify feature (which would require renaming of the corresponding zoomify folder.
