### ISSUE TITLE
Style Species Title on Page

### ISSUE THREAD

**Issue by philipbjorge** [huddlej/pnwmoths#114]
Update the title on species pages as follows...
    <i>Latin Name</i> - Authority
    Common Name

**Comment by huddlej** [comment]
This may be the same issue referenced by issue #63. We're using Yahoo's reset css to standardize across browsers, but by default it resets all styles like strong, emphasis, and underline.

**Comment by philipbjorge** [comment]
Merrill emailed me about this - he wants users to be able to underline, italicize, and bold the species' latin names (not just the factsheet text).

**Comment by huddlej** [comment]
Anything HTML styling not in the factsheet text is part of a Django template which isn't editable by users.

Are there some examples of where the species names should be italicized or bolded that aren't in factsheet text?

**Comment by philipbjorge** [comment]
Since this feature has been merged, I'm closing this ticket.
