### ISSUE TITLE
Add 1-to-1 between species and page

### ISSUE THREAD

**Issue by philipbjorge** [huddlej/pnwmoths#118]
For example,
pnwmoths.biol.wwu.edu/browse/family-noctuidae/subfamily-plusiinae/tribe-plusiini/autographa/autographa-californica/

Some similar species are getting blank href tags - `<a href="">Sim</a>`

**Comment by philipbjorge** [comment]
This is caused by an empty "Id" field in the Page's advanced settings.
I'm not sure how widespread this is... It'd be trivial to write a script to fix all the SQL data, but it might be better to change how we do this. I will look into the template tags...

**Comment by philipbjorge** [comment]
Well, looks like the other option is to give a relation as follows...
Species has a page.

I'd probably vote for the mysql script.

**Comment by huddlej** [comment]
Admittedly using the id field from the page is a bit of a hack to get page urls from the Django template. There might be a cleaner way of doing this now with Django CMS 2.1.1.

I'm not sure I follow your last comment though. What do you mean by "...give a relation as follows..."?

In any case, I think the next step is to get you login access to the production server. :)

**Comment by philipbjorge** [comment]
A model script to fix this issue (filtering could be changed etc). You can just type this into the `./manage.py shell`

`from cms.models import Page
p = Page.objects.filter(reverse_id=None)
for i in p:
    i.reverse_id = i.get_title()
    i.save()`

**Comment by huddlej** [comment]
I've applied a slightly modified version of that script which looks like this:

```
for i in pages:
    if "factsheet" in i.template:
        name = i.get_title().split()
        if len(name) > 1:
            i.reverse_id = i.get_title()
            i.save()
```

This takes into account only factsheet/species pages which are the only ones we need to access by reverse id dynamically.

Maybe we could auto-populate the reverse id field from the title when new factsheet pages are created?

**Comment by philipbjorge** [comment]
I tried to extend the Page model's save method, but had no luck.
I'll keep looking into it.

**Comment by philipbjorge** [comment]
John,
So I've looked at this again and came up with a couple (possible) solutions.
1. Add a one-to-one relationship between species models and page models. Then, a species would always be tied to its page.
2. Somehow extend the Page model's save method (I don't really have a good idea of what's possible/not possible here though?)

I think #1 is actually the best solution because it makes the connection between a species and its page explicit (which was naturally how I assumed it worked until I found out about the reverse_id thing).

Any thoughts?

**Comment by huddlej** [comment]
I think 1-to-1 relationship is the simplest and most intuitive. Extending Page model is like going down the rabbit hole...

**Comment by philipbjorge** [comment]
I'll have this completed soon in my side branch (which is nearly ready for a merge). The following script will work for migration.

```
from cms.models import Page
from species.models import Species

for s in Species.objects.all():
    try:
        s.factsheet = Page.objects.get(reverse_id=s.name)
        s.save()
    except (Exception):
        print "FK Migration failed for ", s.name
```
