### ISSUE TITLE
Make list filters on SpeciesRecord admin page more useable

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#121]
The list filters on the right side of the Django admin list view for SpeciesRecord are very long because there are so many states, counties, etc.

Make each filter a collapseable/expandable list which defaults to collapsed. jQuery is probably the easiest/best tool as its included already in Django admin.

**Comment by philipbjorge** [comment]
I found a nifty snippet on stackoverflow that does this pretty well. I'll implement it.
http://stackoverflow.com/questions/6086651/minimize-the-list-filter-in-django-admin

**Comment by huddlej** [comment]
I like this a lot. Let's see if it works!
