### ISSUE TITLE
Add a key/value table for Species, SpeciesImage, and others

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#122]
Species, images, and other models will have a lot of metadata associated with them that won't be available for every record. These data shouldn't be added directly to these models because they will turn the models into long lists of attributes which are mostly empty.

Instead, a key/value store that can attach via a GenericForeignKey to any model will allow new attributes to be added/deleted dynamically to any model. This functionality would be most easily added with an existing third-party Django app like [django-expando](https://github.com/tuttle/django-expando).

**Comment by philipbjorge** [comment]
As it stands, these models don't have a lot of extra metadata. This is most likely due to the pain of doing data entry, lack of extra data, and an inability to display generic data.

I'm closing this for now until a need arises in the future.
