### ISSUE TITLE
Add cron_job to update our search index

### ISSUE THREAD

**Issue by philipbjorge** [huddlej/pnwmoths#136]
You should cron up a ./manage.py update_index job at whatever interval works best for your site (using --age=<num_hours> reduces the number of things to update).

This way the search functions properly when pages are added, changed, deleted.

**Comment by huddlej** [comment]
There should already be a cron job for updating the search index on
the production site. Whether it's running or not is a different
question. You can check the /etc/crontab to confirm though. If it
isn't there, it might be worth asking Dan Van Pelt if the crontab gets
overwritten by any automated processes.

/John/

On Sat, Feb 11, 2012 at 11:35 PM, Philip Bjorge
reply@reply.github.com
wrote:

**Comment by philipbjorge** [comment]
John,
I checked root, www, huddlej, and bjorgep's crontab but all were
empty. Is their another user I should check?

Philip Bjorge
Studying Computer Science at Western Washington University
http://www.philipbjorge.com

On Feb 12, 2012, at 4:37 PM, John Huddleston
reply@reply.github.com
wrote:

**Comment by huddlej** [comment]
Check /etc/crontab.

/John/

On Sun, Feb 12, 2012 at 4:49 PM, Philip Bjorge
reply@reply.github.com
wrote:
