### ISSUE TITLE
Upgrade Django-CMS

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#14]

**Comment by philipbjorge** [comment]
I'll look into upgrading to 2.2 soon. It has a lot of compelling reasons to upgrade.

**Comment by philipbjorge** [comment]
Django-cms 2.2 runs only with Django 1.3 (contrary to its documentation). I couldn't get my dev server to smoothly upgrade.

**Comment by philipbjorge** [comment]
Finally got 1.3.5 installed and Django-cms 2.3.5
