### ISSUE TITLE
Setup a development server

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#18]

**Comment by philipbjorge** [comment]
"Thinking ahead to when we might want to expand the site, it seems like we need a copy of the entire site to serve as a development site, on which we can work without the changes showing up on published site.  Then, once the changes have been updated, we could swap the expanded site for the existing siting.  It'd be great if you could spend some time thinking about how to do this, get it set up, and leave a detailed set of instructions for doing the swap."

**Comment by philipbjorge** [comment]
Static site is being hosted through apache.
Dev site is being hosted at a named subdomain domain with apache/django.
