### ISSUE TITLE
Create Unison Install Instructions

### ISSUE THREAD

**Issue by philipbjorge** [huddlej/pnwmoths#228]
Or a script for OSX?

**Comment by philipbjorge** [comment]
This should be an installation script instead.
Need to allow non-wwu connections for ssh so that Chris can upload images.

**Comment by philipbjorge** [comment]
Non-wwu connections is not an option so that leaves only HTTP.
Might opt for this instead of unison when on non-osx systems.

**Comment by MatteBailey** [comment]
Is this something that still needs to be addressed?

**Comment by philipbjorge** [comment]
Yes - Sign up at https://bitbucket.org and give me your account name so I can send you the private repository.
