### ISSUE TITLE
Document Look+Feel and create a FAQ page

### ISSUE THREAD

**Issue by philipbjorge** [huddlej/pnwmoths#240]
FAQ will include details on:
- administering the server
- where files are located (including django cms's stuff)
- how to find the root classes/templates for things like django cms
- how to get a copy of the dev virtual machine
- how to use the vm

**Comment by philipbjorge** [comment]
@MatteBailey - Do you want to tackle the look+feel aspect next?

Write a wiki page with the following information:
1. The locations of the header image, the navigation images, and the 3 slider images (probably starting with /static/media)
2. The location of the main CSS file that defines the site's general colorscheme (There are page specific styles somewhere too, maybe css_pages).
3. We don't have images yet, but it'd be nice if you could make an unofficial sawflies and butterflies header and upload them. It'd make using the sites easier.
4. Document how you uploaded them. (I'll email you about this).

Example Header:

```
---------------------------------------------------------
| SS                                              tt  |
---------------------------------------------------------
```

where SS is maybe a single sawfly image from google and tt is some text saying - temporary/we don't own this image. You should be able to just overwrite the old images (don't do this for moths lol).

**Comment by MatteBailey** [comment]
I'll finish this up today or tomorrow. I've began a page entitled "Look and Feel" under the Website category.

**Comment by philipbjorge** [comment]
It's looking good so far!

**Comment by MatteBailey** [comment]
I think Look and Feel is complete now. Take a look and let me know if anything needs to changed or added.

**Comment by philipbjorge** [comment]
Looks good to me. Nice work!

**Comment by philipbjorge** [comment]
I will let you have the honors of closing this...

**Comment by MatteBailey** [comment]
What about last two bullets for the FAQ? Do we still need to do those?

**Comment by philipbjorge** [comment]
Do you want to fill those in?

Assuming you get the latest code running, I think we can call that the "canonical" VM so to speak. So I'd make a copy that you don't work in and have that ready to share.

Getting copies would probably amount to emailing you. Or you could scp the VM to somewhere on the server. Do this when your on campus though otherwise it will be very slow.
