### ISSUE TITLE
Distorted Images On Species Page

### ISSUE THREAD

**Issue by MatteBailey** [huddlej/pnwmoths#247]
On PNWSawflies and probably PNWButterflies, uploaded jpgs of species on the species page are distorted until the thumbnail of the image is clicked. This seems to be an issue with zoomify.

**Comment by philipbjorge** [comment]
More accurately this a CSS issue (probably).
If you mess about in the Chrome Inspector it'll probably have something to do with the CSS (maybe with its height or max-width properties) - Worst case you can fix the size with javascript after clicking the image in the carousel.

**Comment by MatteBailey** [comment]
Yeah, the image has alt height="93". It's also loading the thumbnail version of the image initially instead of the full resolution version.

**Comment by MatteBailey** [comment]
Initially, http://url/media/moths/cache/species_img.jpg.141x93_q95.jpg is the image being linked, and after clicking the thumbnail this changes to http://url/media/moths/cache/species_img.jpg.376x249_q95.jpg. Starting it as this should fix the problem. I'll have to look at how the images are being loaded initially and make a change there.

**Comment by philipbjorge** [comment]
Oh interesting. That's happening inside the factsheet template.
You'll be ready to fix this one this week.

**Comment by MatteBailey** [comment]
The issue is partially arising in this line in factsheet.html:

`<div id="old-image-factsheet" class="hidden"><a href="{{ species_image.image.url }}">{{ species_image.thumbnail_img }}</a></div>`

If we use medium_img instead of thumbnail_img the distortion isn't as severe, but I haven't totally confirmed that it doesn't break anything else yet. Still, instead of scaling the initial image to a forced resolution, it would probably be better to scale it down within a certain range while retaining original aspect ratio.

**Comment by MatteBailey** [comment]
I changed the line to:

`<div id="old-image-factsheet" class="hidden"><a href="{{ species_image.image.url }}"><img src="{{ species_image.medium_url }}" /></a></div>`

Everything appears to be working correctly now.

**Comment by philipbjorge** [comment]
Good work. Feel free to close this one after you get the changes propagated (see your email).
