### ISSUE TITLE
Update Lucid 3.3 before publishing key

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#35]

**Comment by philipbjorge** [comment]
Need to make sure I find out any issues related to this before nearing "crunch time."

**Comment by philipbjorge** [comment]
So, no issues with exporting the key. This should be a quick drop-in before launch.
The only thing to consider is that Lucid 3.3 exports a Java application that's compatible with most computers, but no mobile devices.
Lucid 3.5 can export a javascript application thats compatible with all browsers (although not the best to use for mobile, it's designed for a full screen).

**Comment by philipbjorge** [comment]
No upgrade for now (maybe if they get a mobile version).
