### ISSUE TITLE
Allow toggling BC regional district boundaries in factsheet maps

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#6]
A digital version of Regional District boundaries is available for free downloading from the Land and Resource Data Warehouse http://www.lrdw.ca/. Municipalities are also available. Just click on "Download Land and Resource Data" and search for "Regional District" -- the "TANTALUS" file is what you need, although the 2006 Census file will also work.

A map site that is also useful is http://www.pac.dfo-mpo.gc.ca/gis-sig/maps-cartes-eng.htm. Just click on the "Mapster" link, and explore the layers under the various folders.

**Comment by philipbjorge** [comment]
Consolidating at #146
