### ISSUE TITLE
Provide web service for map data

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#61]

**Comment by huddlej** [comment]
Although there is no publicly documented web service. This has been effectively fixed as of aaa6f7dcc56d400a2dbf499b73e38dbe72e0810d with the introduction of tastypie.

This ticket could be closed with some small configuration of tastypie and documentation for users.

**Comment by philipbjorge** [comment]
http://pnwmoths.biol.wwu.edu/dokuwiki/doku.php?id=website:data_service

Preliminary Docs (Will be expanded on when we know what data should be made available through the API).
