### ISSUE TITLE
Add author and year to the top of each species account

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#62]

**Comment by huddlej** [comment]
Author and year could be part of the database. Since they describe a species, they could be added directly to the Species model. The author attribute of a Species model should be a foreign key to an Author table to support one author to many species.

**Comment by philipbjorge** [comment]
I'm going to call this the Authority relation. I won't be splitting up name and year though because of the variation in formatting. For example:
(Hübner, 1796)
(Hübner, [1813])
Hübner
Hübner, [1813]

**Comment by huddlej** [comment]
Is the variation in formatting necessary or just historical? As far as display on the site goes, we should pick a format and stick with it. Also, do we need full names for people?

These are probably Merrill questions...

**Comment by philipbjorge** [comment]
I _think_ the variation in formatting was necessary - I'll ask Merrill though and comment with his reply.

Edit:
"It'll be varied - we should use the entries exactly as they are in the spreadsheet."
Merrill

**Comment by huddlej** [comment]
Perfect. Works for me!

**Comment by philipbjorge** [comment]
Because the code for this has gotten merged and all that remains is importing the data, I'm going to close this issue.
A script for importing the data can be found in #120.
