### ISSUE TITLE
County boundary lines should be thinner

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#71]

**Comment by philipbjorge** [comment]
John
This change needs to be made inside the kmz files on your server.
Do you just want me to email these to you when I get these done (probably after Christmas)?

**Comment by huddlej** [comment]
The KMZ files are in the repository under /www/media/kml/. KMZ files are just zipped KML files, so you can access the contains by first running "unzip" on each file.

The best solution would be to update the javascript to no longer refer to the files in my home directory. The GGeoXml class takes an absolute url, so you'd just need to find a way to supply that to the script dynamically. A very simple way would be to provide the url in the DOM through a Django template. There might be better ways now though...

Also, check out the "Specimen Collection Metadata" page in the wiki for more details on how the KML/KMZ files are created.
