### ISSUE TITLE
Show any data point with a species name and lat/lng values on maps

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#73]
This means any SpeciesRecord (in the Django version of the site) which is less ambiguous than it was with CouchDB where records only had nominal types.

**Comment by philipbjorge** [comment]
John - I think you can close this issue. 
1. The django-cms requires any records to have a species name, lat, and long.
2. The map data is composed of all species with the page's species name.
3. The map displays all data (no matter how few or many other fields are filled in - county, etc).
So, all data points are rendered.

First, I tested this by reasoning my way through the javascript and data. Second, I started with a species with no records and began adding data points with various levels of competeness.

**Comment by philipbjorge** [comment]
This also looks like a duplicate of #2   (I performed similar testing).

**Comment by huddlej** [comment]
This is a trickier ticket than I've described it here. What it really means is related to the color of the map markers which you recently commented on. The original idea was that any Django model with a lat/lng would behave polymorphically as a potential map data source. For example, if we add a FieldNotes or SightRecord model with lat/lng attributes, those values should populate the map too.

For now, this ticket can stay open but just not be "critical".

**Comment by huddlej** [comment]
Nevermind, it looks like Merrill'd prefer to keep labels separate. We can handle this type of issue as it arises in the future. #2 is still a separate, open issue.
