### ISSUE TITLE
Include specimen source in specimen model (e.g., OSU, etc.)

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#77]

**Comment by philipbjorge** [comment]
Can you expand on what this ticket means?

**Comment by huddlej** [comment]
Thinking about this now, I can't remember how this is different from the "collection" attribute in SpeciesRecord. Specimens are part of larger collections which are usually house at universities but sometimes in personal residences.

The main point of recording the source of the specimen is to provide credit for the specimen on the website. Merrill will have suggestions for how to best provide this credit. You can see if having "OSU" in the database is enough to satisfy this requirement.

**Comment by philipbjorge** [comment]
I'm closing this because according to Merrill, collection/collector are the same as specimen source.
