### ISSUE TITLE
Prevent image hotlinking

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#80]

**Comment by philipbjorge** [comment]
This is a pretty simple .htaccess rule.
http://www.javascriptkit.com/howto/htaccess10.shtml

**Comment by philipbjorge** [comment]
With zoomify, I don't think this will even be an issue.
Add hotlink protection for moths/ directory.

**Comment by philipbjorge** [comment]
Hotlink protection has been enabled.
