### ISSUE TITLE
Update Google Maps to API version 3

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#85]

**Comment by philipbjorge** [comment]
we should seriously look into this when adding the moth plates and to improve mobile support.

**Comment by philipbjorge** [comment]
Issue #53 and #67 are still incomplete but have been merged into this ticket as they will be fixed when we upgrade to maps v3.

**Comment by philipbjorge** [comment]
Preliminary Conversion Research:

tabbed infowindows
- convert these to infobubbles
  http://google-maps-utility-library-v3.googlecode.com/svn/trunk/infobubble/examples/example.html?compiled

hybrid/terrain/moving controls
- native v3

polygon around PNW area
- native v3

lightweight markers
- http://groups.google.com/group/google-maps-js-api-v3/browse_thread/thread/c4f90346ab9b36c7?fwc=1

fullscreen
- same as how its currently done

filters
- Need to look into this further.

**Comment by philipbjorge** [comment]
Prototype:
http://jsfiddle.net/X5r8r/294/
