### ISSUE TITLE
Remove Django CMS tiled image behind p tags in species accounts

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#91]
The Django CMS "p" tag image from the in-site editor is tiled behind paragraph tags on the following pages:

Euthyatira pudens
Caenurgina crassiuscula
Arctia opulenta
Sphinx poecila

**Comment by philipbjorge** [comment]
Is this a common enough problem that we should upgrade wymeditor? I'm guessing it might be a copy/paste bug?
I fixed the offending pages and am including the following regular expression to help make it easier to fix in the future.

```
( style="[^>]+>)
```

This regex matches " style="ANYTHING">" and you can then replace everything it matches with ">".
Sometimes a div tag is created, so manually delete the opening <div> and closing </div> (beginning and end of file).

This is a pretty bruteforce method and assumes no CSS styling.

**Comment by huddlej** [comment]
I don't think this is a common problem although it could become one if it's really a copy/paste issue.

wymeditor is bundled with Django CMS, so we'll upgrade the former when we upgrade the latter.
