### ISSUE TITLE
Similar species don't display properly for Hypena humuli

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#92]
This problem is probably not specific to this species. Another example: Microhelia angelica

**Comment by philipbjorge** [comment]
John
This is an issue with bad data being entered in the species' records.
In Hypena humuli's case, someone has entered a month of 15.

I'm going to add a constraint to the speciesrecord model and a javascript alert on bad data to the phenology chart javascript.

**Comment by huddlej** [comment]
Nice catch! I will probably remove the alert just to prevent users from getting spammed if there's an unintentional import of bad data. Your changes to the models should handle this problem farther upstream anyway.
