### ISSUE TITLE
Fullscreen image viewing breaks on second load

### ISSUE THREAD

**Issue by huddlej** [huddlej/pnwmoths#95]
To recreate:
1. Open a species factsheet
2. Click on the main image to zoom in
3. Close the zoomed image
4. Click on the main image again

The second attempt fails to load the zoomed image.

**Comment by philipbjorge** [comment]
I can't reproduce this bug - can you confirm that it still exists or close this?

**Comment by huddlej** [comment]
I think one of us may have inadvertently fixed this since I opened this ticket. :)
